### ISSUE TITLE
Fix numbers being too small to appear as bars

### ISSUE THREAD

**Issue by Thunder2103** [Thunder2103/Algorithms-Visualiser#27]
The numbers 1 and 2 (and possibly 3) are to small to be seen as bars on screen 

## Fixes: 
    - Stretch length of bars slightly (will reduce the largest number that can be displayed on screen)
    - Stretch the length of the bars when they are equal to 1, 2 (and maybe 3) only so they are the same length as a bar with value 4 
       (smallest value that has been displayed). Could cause confusion to user because values will look the same 
    - Don't fix and leave as is (could cause confusion if user enters 1,2 or 3 and it looks like nothing happened...)

**Comment by ricardoholmes** [comment]
I'd suggest reworking the whole bar height calculation. You could make it such that the current biggest value is given the maximum height, and if a bigger value is added then everything shrinks dynamically.
Also the max allowed value should be <= the max allowed height (in pixels) so that everything fits and no two values have the same height.

**Comment by Thunder2103** [comment]
cheers

**Comment by Thunder2103** [comment]
I reworked the equation based on your suggestion (it took a while cause I had a week off).  Having everything grow and shrink dynamically is a far better solution and looks much nicer.
